CREATE TABLE available_assets_mig_v1 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mouza VARCHAR2(255),
    asset CLOB,
    asset_type VARCHAR2(255),
    dag_no VARCHAR2(255),
    acre NUMBER(15, 4),
    sq_ft NUMBER(15, 4),
    status CHAR(1) DEFAULT 'A',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
